### PR TITLE
Creates the function to set external API key

### PR DESCRIPTION
**Pull request by ankur0904**
Implemented the `set_apikey` function within the `Client` class to set the different external API keys. 

```
def set_apikey(self, openai_key: Optional[str] = None, cohere_key: Optional[str] = None, huggingface_key: Optional[str] = None, palm_key: Optional[str] = None):
    ...
```

This PR can close the issue #382

cc @tsmith023 @databyjp

### CODE REVIEW

**Review by tsmith023 — CHANGES_REQUESTED** [review]
I like the changes, they look correct and the docstring is helpful. Could you please also add tests for your changes? I think unit tests will suffice so adding some simple ones to `test/test_client.py` under the `test_timeout_config` test would be great!

Cheers 😁

**Comment by tsmith023** [comment]
Note also the `mypy` errors in the CI pipeline. If you've not used `mypy` before then they're telling you that your function needs to have a return marked, i.e. `-> None:` and it cannot determine the type of `_headers`, which I think is solvable by adding `self._headers: Dict[str, str] = {}` [here](https://github.com/ankur0904/weaviate-python-client/blob/848c5d664e624098bb4d84074a1640a9f144ea51/weaviate/connect/connection.py#L116)

**Comment by ankur0904** [comment]
@tsmith023 Thanks for the review. Soon making the desired changes.

**Comment by ankur0904** [comment]
@tsmith023
Hi Tommy
I have made the following changes-
-  Add `self._headers: Dict[str, str] = {}` line in connect/connection.py file
-  Add `-> None` in the function signature

Thanks
Ankur

**Comment by ankur0904** [comment]
I am unable to add the `tests` in the required file. I am afraid that it will take some time because I have my University exams.

**Comment by ankur0904** [comment]
@tsmith023 I have added unit tests.

**Comment by tsmith023** [comment]
> I have my University exams

You should concentrate on these first! The PR can stay open until you have time to resume it, there's no pressure 😁

**Comment by ankur0904** [comment]
> > I have my University exams
> 
> You should concentrate on these first! The PR can stay open until you have time to resume it, there's no pressure 😁

Thanks for the patience, I am now available. If there are any changes required then please let me know.

**Comment by ankur0904** [comment]
@tsmith023 Any feedback regarding the PR.

**Comment by tsmith023** [comment]
Hi @ankur0904, sorry for not replying promptly! Because the CI pipeline is not fully green, it needs to be fixed before I will review it again. Could you look into the linting problems and unit test failures? Cheers 😁

**Comment by ankur0904** [comment]
@tsmith023 Ofcourse I will look into the failing CI pipeline.

**Comment by ankur0904** [comment]
Hey @tsmith023 any other changes required?

**Comment by databyjp** [comment]
> Hey @tsmith023 any other changes required?

Hi @ankur0904 - I can see that quite a few tests are failing here. Please take a look at the individual pipelines to see what is failing and try to address them.

As you can imagine, libraries like this one are our core products. And these automated tests are important parts of our quality assurance processes that help us ensure that any potential bugs or regressions do not get introduced into our products. 

If you click on the `Details` tab in the PR CI checklist, you can see the logs and stack trace, which should help you to see what is failing. 

I see that the pipeline indicates the linting process to be failing, and some unit tests. 

You can run these tests locally before committing / testing the changes through the CI/CD pipeline. You might have read this already, but the [contributor guide](https://github.com/weaviate/weaviate-python-client/blob/main/CONTRIBUTING.md) includes a section on linting, and tests. So, please review these sections, and run those tests locally, which should mean that they pass on GH. 

I hope that helps!

**Comment by ankur0904** [comment]
@databyjp Thanks for the guidance. 

I checked each CI pipeline test, I found this test **failure** and confused how to fix it?

After running 
```bash
$ pytest test --full-trace
```

```bash
self = <weaviate.client.Client object at 0x7f00886e77f0>, openai_key = 'your_key'
cohere_key = None, huggingface_key = None, palm_key = None

    def set_apikey(self, openai_key: Optional[str] = None, cohere_key: Optional[str] = None, huggingface_key: Optional[str] = None, palm_key: Optional[str] = None) -> None:
        """
        Set the external API key.
    
        Parameters
        ----------
        openai_key: str, optional
            It is OpenAI API key.
        cohere_key: str, optional
            It is Cohere API key.
        huggingface_key: str, optional
            It is Hugging Face API key.
        palm_key: str, optional
            It is Palm API key.
    
        Returns
        -------
        None
        """
        if openai_key:
>           self._connection._headers["x-openai-api-key"] = openai_key
E           TypeError: 'Mock' object does not support item assignment

cohere_key = None
huggingface_key = None
openai_key = 'your_key'
palm_key   = None
self       = <weaviate.client.Client object at 0x7f00886e77f0>

weaviate/client.py:320: TypeError
```
**Related File**: 
`client.py`

**P.S.** Meanwhile, I have fixed the `linting issue`.


Thanks 
Ankur

**Comment by dirkkul** [comment]
superseeded by https://github.com/weaviate/weaviate-python-client/pull/981

**Pull request closed without merging**
