### PR TITLE
add schema.exists

### PR DESCRIPTION
**Pull request by StefanBogdan**

### CODE REVIEW

**Review by dirkkul — APPROVED** [review]

**Comment by chengyineng38** [comment]
Which release is this going to be part of? Used `3.17.1` but got the error that schema doesn't have the method exists.

**Comment by dirkkul** [comment]
The next one, probably 3.18.0

**Comment by dirkkul** [comment]
Checking again: This should already be included in 3.17.0 and works locally

**Comment by StefanBogdan** [comment]
I checked as well and it works starting version `3.17.0`.

**Pull request merged**
