### PR TITLE
add tenant as an optional param to batch.delete_objects

### PR DESCRIPTION
**Pull request by ciprianaradulescu**
Fix for https://github.com/weaviate/weaviate-python-client/issues/374

### CODE REVIEW

**Comment by dirkkul** [comment]
Hi @ciprianaradulescu ,

thank you for your contribution! Could you add a test under integration/test_batch.py? You could just extend `test_add_object_batch_with_tenant`

**Comment by ciprianaradulescu** [comment]
Hello @dirkkul ,

I've extended `test_add_object_batch_with_tenant` to check for both a valid and an invalid batch delete based on the tenant. Please let me know if it looks ok.

Thank you !

**Comment by ciprianaradulescu** [comment]
I agree with the CLA.

**Comment by dirkkul** [comment]
Hi @ciprianaradulescu, thank you, test looks good! Could you let black run over your code? The [contributing guide](https://github.com/weaviate/weaviate-python-client/blob/main/CONTRIBUTING.md) shows how to do it.

I'll merge afterwards

**Comment by ciprianaradulescu** [comment]
Yeah, sorry, missed that 😁 Should be fine now.

**Pull request merged**
