### PR TITLE
Close possibly open objects

### PR DESCRIPTION
**Pull request by abhishek-compro**
This is mostly a refactor. Let me know if there are any conflicting opinions.

### CODE REVIEW

**Comment by abhishek-compro** [comment]
@weaviate-git-bot I agree to the [Contributor License Agreement](https://weaviate.io/service/contributor-license-agreement)

**Comment by abhishek-compro** [comment]
This is a very simple change but looks complicated in the default diff view. After you enable *Hide whitespace* in the diff view settings on GitHub you will be able to view only the lines that were added and removed.

**Comment by dirkkul** [comment]
HI @abhishek-compro , thanks for your contribution! There are some type-checking failures, could you please adress them?

**Comment by abhishek-compro** [comment]
> HI @abhishek-compro , thanks for your contribution! There are some type-checking failures, could you please adress them?

Done

**Comment by abhishek-compro** [comment]
@dirkkul I have run the tests as per the contributing guide and it only gives some warnings but no errors. I am using version 1.24.1.

https://github.com/weaviate/weaviate-python-client/actions/runs/8684237813/job/23851552307?pr=985#step:6:1286

I don't know how to fix address that is already in use. Is it something specific to my changes?

**Review by dirkkul — APPROVED** [review]

**Comment by dirkkul** [comment]
> I don't know how to fix address that is already in use. Is it something specific to my changes?

that is sadly a flaky CI test, should not be connected to your changes

Thanks for your contribution, merged :)

**Pull request merged**
